### ISSUE TITLE
Milestones for the Hack Suite

### ISSUE THREAD

**Issue by ZenythFactor** [phase/sbhs#3]
alright, so I've made a special list of goals for the project we can look around. If you could, you set this issue as some sorta of milestone.

**Major Goals:**

- [x] Make every playable character sprite doable for customization
- [x] Eggman and Phis can be edited
- [ ] Every character's stats can be changed
- [ ] Hitboxes and Hurtboxes can be edited
- [ ] Arena textures can be swapped 
- [x] Story dialogue can be edited

**Minor Goals:**

- [ ] Story Art can be altered
- [ ] Skill Cards stats can be changed
- [ ] Sprite canvas can be resized to it's possible max
- [x] Effects sprites can be edited
- [ ] entire arenas can be changed
- [ ] event areas can be placed anywhere in Story Mode
- [ ] map graphics can be changed

**Dream Goals:**

- [ ] every graphic can be altered, from title to final credits
- [ ] option to add custom character/arena slots
- [ ] option to add custom chapters in Story Mode
- [ ] option to add custom Skill Cards
- [ ] option to add more custom Enemies and Boss characters beyond Phis and Eggman
- [ ] feats to push the game further than its former.

_edited by Phase for formatting_

**Comment by lavendertheghost** [comment]
I would love full graphics editing, that would be nice. But priorities lie in the major and minor goals.

**Comment by phase** [comment]
You can edit most the graphics in the game with [unLZ-GBA](https://www.romhacking.net/utilities/362/). Graphics like character sprites are encoded in their own way, which this suite will allow editing of. I would love to make a 3D map editor. That's a hella long term goal though. The top two goals are almost done, just need to finish a couple characters.
